const item = {
  id: "ce327a1e-0d55-4cb2-8f69-a2d977b79bc3",
  name: "Keto Corn Dog Bites",
  tags: [
    "meal-plan-ok",
    "kid-friendly",
    "dairy-free",
    "gluten-free",
    "wheat-free",
    "peanut-free",
    "fish-free",
    "shellfish-free",
    "pork-free",
    "chicken-free",
    "keto",
    "lchf",
    "relevant-meal--snacks",
    "snacks",
  ],
  description:
    "Looking for keto sides and snacks to add to your summer barbecues or meal plans? Corn dog bites are perfect for adults and kiddos! Despite the batter being non-traditional, you really can’t tell the difference in taste. They taste even better dipped in your favorite hot dog condiments! Jessica L.",
  prepareTime: 17,
  cookTime: 28,
  ingredients: [
    {
      name: "Raw Egg",
      servingSize: {
        units: "large",
        desc: "4 large",
        qty: 4,
        grams: 200,
        scale: 4,
      },
    },
    {
      name: "Almond Flour",
      servingSize: {
        units: "cup",
        desc: "1 cup",
        qty: 1,
        grams: 112,
        scale: 1,
      },
    },
    {
      name: "Almond Milk, Plain Or Original, Unsweetened",
      servingSize: {
        units: "cup",
        desc: "½ cup",
        qty: 0.5,
        grams: 120,
        scale: 0.5,
      },
    },
    {
      name: "Salt",
      servingSize: {
        units: "teaspoon",
        desc: "¼ teaspoon",
        qty: 0.25,
        grams: 2,
        scale: 0.25,
      },
    },
    {
      name: "Hot Dog, Beef (Kosher), Plain",
      servingSize: {
        units: "regular - 10 per pound",
        desc: "3 regular - 10 per pound",
        qty: 3,
        grams: 135,
        scale: 4.762,
      },
    },
  ],
  steps: [
    "Preheat an oven to 350 degrees. Separate HALF your total eggs. Set the egg whites into a stand mixer with a whip attachment and set the egg yolks aside for later. Whip the egg white to stiff peaks and set them aside in a small bowl.",
    "Wipe your mixing bowl clean. Place in the egg yolks set aside earlier and whip them until they thicken and become a light, opaque yellow (this can take up to 5 minutes). Then, whip in the almond flour until you have a crumbly paste.",
    "Whip into the mixing bowl your remaining whole eggs, almond milk, and salt. Once fully mixed, remove your bowl from your stand mixer. Use a spatula or hand whisk to gently fold in the stiff egg whites you set aside earlier.",
    "Line a 12-count muffin tin with cupcake liners. Remove the rounded ends of your hot dogs. Slice each hot dog into 4 pieces (one piece for each muffin tin). Place each piece of hot dog standing up in the center of each muffin tin.",
    "Use a spoon or scoop to transfer the liquid batter over each hot dog, filling each cupcake liner about ¾ full.",
    "Bake the corn dog bites for 25-28 minutes, until you seen golden brown tops. Enjoy with your favorite mustard or a squirt of ketchup!",
  ],
  servings: 6,
  servingSizes: [
    {
      scale: 1,
      qty: 1,
      grams: 74,
      units: "2 corn dog bites",
    },
  ],
  nutrients: {
    caloriesKCal: 232.535,
    caloriesKJ: 972.927,
    totalCarbs: 4.809,
    diabetesCarbsADA: 4.809,
    netCarbs: 2.726,
    diabetesCarbs: 2.755,
    fiber: 2.025,
    starch: 0.16,
    sugar: 1.46,
    addedSugar: 0.668,
    sugarAlcohols: 0.058,
    protein: 10.835,
    fat: 19.47,
    transFat: 0.377,
    monousatFat: 10.507,
    polyunsatFat: 3.024,
    omega3Fat: 0.046,
    omega6Fat: 2.979,
    saturatedFat: 4.379,
    cholesterol: 137.383,
    vitaminA: 62.894,
    vitaminC: 0,
    vitaminD: 1.137,
    vitaminE: 5.516,
    vitaminK: 1.158,
    vitaminB1: 0.077,
    vitaminB2: 0.38,
    vitaminB3: 1.186,
    vitaminB5: 0.601,
    vitaminB6: 0.095,
    vitaminB12: 0.586,
    potassium: 273.321,
    magnesium: 56.388,
    calcium: 105.155,
    iron: 1.355,
    zinc: 1.372,
    copper: 0.208,
    phosphorus: 177.449,
    sodium: 350.392,
    selenium: 13.284,
    folate: 23.416,
    choline: 114.639,
    alcohol: 0,
    caffeine: 0,
    gluten: 0,
    manganese: 0.388,
    conjugatedLinoleicAcid: 0.04,
    phyticAcid: 176.61,
    xylitol: 0,
    isomalt: 0,
    sorbitol: 0,
    maltitol: 0,
    lactitol: 0,
    erythritol: 0,
    pinitol: 0,
    inositol: 0.058,
    mannitol: 0,
  },
  image:
    "https://tinyurl.com/2p82zzca/ce327a1e-0d55-4cb2-8f69-a2d977b79bc3.png",
};
//const url = 'https://low-carb-recipes.p.rapidapi.com/recipes/ce327a1e-0d55-4cb2-8f69-a2d977b79bc3';

function TryitoutDetails({}) {
  return <div>render Details Content</div>;
}

export default TryitoutDetails;
